### ISSUE TITLE
php7.2-mcrypt error

### ISSUE THREAD

**Issue by sanddevil** [Oefenweb/ansible-php-cli-ondrej#11]
PHP 7.2 appears broken. When attempting to install PHP 7.2 I get the following error:

failed: [default] (item={u'name': u'mcrypt'}) => {"changed": false, "item": {"name": "mcrypt"}, "msg": "No package matching 'php7.2-mcrypt' is available"}

It looks like ondrej's repo doesn't contain the mcrypt mod and there doesn't appear to be an easy way of deselecting mcrypt in your package. 

Cheers :)

**Comment by tersmitten** [comment]
That's right. `mcrypt` was deprecated in 7.1 and removed in 7.2.

See [`php_cli_ondrej_mods_present`](https://github.com/Oefenweb/ansible-php-cli-ondrej/blob/master/tests/test.yml#L18) for mods that you want to install (and enable)

**Comment by sanddevil** [comment]
Great - thanks for the fast response! I couldn't figure out how to exclude mcrypt and your test script shows me - so thanks for the link. Much appreciated!
