### ISSUE TITLE
version_compare filter is now removed and fails with Ansible 2.9.0

### ISSUE THREAD

**Issue by sanddevil** [Oefenweb/ansible-php-cli-ondrej#13]
The line 
`php_cli_ondrej_serialize_precision: "{{ -1 if (php_cli_ondrej_version | version_compare('7.1', '>=')) else 17 }}"`
now breaks the role since it contains the removed version_compare filter which was originally deprecated on Ansible version 2.5.0

**Comment by tersmitten** [comment]
Can you make a PR to fix it?

**Comment by tersmitten** [comment]
It looks like you're using an old version

https://github.com/Oefenweb/ansible-php-cli-ondrej/commit/1162e17ed5deb25c82b419cab4fc95d3fbf8f3a9

**Comment by sanddevil** [comment]
Hmm yes that certainly looks the case. I'll do some tests this evening but I believe you are correct thanks 👍
